services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`frontend.zerobase.tech`)'
      - 'traefik.http.routers.frontend.entrypoints=web'
    networks:
      - web

networks:
  web:
    external: true
