import {
  HomeIcon,
  SchoolIcon,
  Clock,
  CalendarDays,
  Library,
  Fence,
  // BookMarked,
  Building2,
  UserPen,
  BookCheck,
  Wallet,
  Database,
  BellRing,
  Settings,
} from "lucide-react";

export const AppMenu = [
  {
    title: "Dashboard Manager",
    href: "/dashboard/managers",
    icon: HomeIcon,
    visibility: true,
  },
  {
    title: "Class Manager",
    href: "/managements/manager/class",
    icon: Building2,
    visibility: true,
  },
  {
    title: "Class Management Manager",
    href: "/managements/manager/class-management",
    icon: Building2,
    visibility: false,
  },
  {
    title: "Keuangan Manager",
    href: "/managements/manager/keuangan",
    icon: Wallet,
    visibility: true,
  },
  {
    title: "Data Siswa Manager",
    href: "/managements/manager/student",
    icon: Database,
    visibility: true,
  },
  {
    title: "Profile Siswa Manager",
    href: "/managements/manager/profile-student",
    icon: UserPen,
    visibility: true,
  },
  {
    title: "Data Guru Manager",
    href: "/managements/manager/teacher",
    icon: Database,
    visibility: true,
  },
  {
    title: "Profile Guru Manager",
    href: "/managements/manager/profile-teacher",
    icon: UserPen,
    visibility: true,
  },
  {
    title: "Pengumuman Manager",
    href: "/managements/manager/pengumuman",
    icon: BellRing,
    visibility: true,
  },
  {
    title: "Pengaturan Admin Manager",
    href: "/managements/manager/setting-admin",
    icon: Settings,
    visibility: true,
  },
  {
    title: "Pengaturan Pembayaran Sekolah Manager",
    href: "/managements/manager/setting-payment",
    icon: Settings,
    visibility: false,
  },
  {
    title: "Pengaturan Profile Sekolah Manager",
    href: "/managements/manager/profile",
    icon: Settings,
    visibility: false,
  },
  {
    title: "Dashboard Admin",
    href: "/dashboard/admins",
    icon: HomeIcon,
    visibility: true,
  },
  {
    title: "Sekolah Admin",
    href: "/managements/admin/school",
    icon: SchoolIcon,
    visibility: true,
  },
  {
    title: "Keuangan Admin",
    href: "/managements/admin/keuangan",
    icon: Wallet,
    visibility: true,
  },
  {
    title: "Data Siswa Admin",
    href: "/managements/admin/student",
    icon: Database,
    visibility: true,
  },
  {
    title: "Data Guru Admin",
    href: "/managements/admin/teacher",
    icon: Database,
    visibility: true,
  },
  {
    title: "Pengumuman Admin",
    href: "/managements/admin/pengumuman",
    icon: BellRing,
    visibility: true,
  },
  {
    title: "Library Digital Admin",
    href: "/managements/admin/library",
    icon: Library,
    visibility: true,
  },
  {
    title: "Dashboard Teacher",
    href: "/dashboard/teachers",
    icon: HomeIcon,
    visibility: true,
  },
  {
    title: "Edit Tugas Teacher",
    href: "/managements/teacher/tasks",
    icon: HomeIcon,
    visibility: false,
  },
  {
    title: "Create Tugas Teacher",
    href: "/managements/teacher/tasks-create",
    icon: HomeIcon,
    visibility: false,
  },
  {
    title: "Materi Teacher",
    href: "/managements/teacher/material",
    icon: Fence,
    visibility: true,
  },
  {
    title: "Create Materi Teacher",
    href: "/managements/teacher/material-create",
    icon: Fence,
    visibility: false,
  },
  {
    title: "Detail Materi Teacher",
    href: "/managements/teacher/material-detail",
    icon: Fence,
    visibility: false,
  },
  {
    title: "Class Teacher",
    href: "/managements/teacher/class",
    icon: Building2,
    visibility: true,
  },
  {
    title: "Presence Teacher",
    href: "/managements/teacher/presence",
    icon: Clock,
    visibility: true,
  },
  {
    title: "Schedule Teacher",
    href: "/managements/teacher/schedule",
    icon: CalendarDays,
    visibility: true,
  },
  {
    title: "Library Digital Teacher",
    href: "/managements/teacher/library",
    icon: Library,
    visibility: true,
  },
  {
    title: "Profile Teacher",
    href: "/managements/teacher/profile",
    icon: UserPen,
    visibility: true,
  },
  {
    title: "Exam Teacher",
    href: "/managements/teacher/exam",
    icon: BookCheck,
    visibility: true,
  },
  {
    title: "Dashboard Student",
    href: "/dashboard/students",
    icon: HomeIcon,
    visibility: true,
  },
  {
    title: "Tugas Student",
    href: "/managements/student/tasks",
    icon: Fence,
    visibility: false,
  },
  {
    title: "Tugas Detail Student",
    href: "/managements/student/tasks-detail",
    icon: Fence,
    visibility: false,
  },
  {
    title: "Materi Student",
    href: "/managements/student/material",
    icon: Fence,
    visibility: true,
  },
  {
    title: "Materi Detail Student",
    href: "/managements/student/material-detail",
    icon: Fence,
    visibility: false,
  },
  {
    title: "Presence Student",
    href: "/managements/student/presence",
    icon: Clock,
    visibility: true,
  },
  {
    title: "Schedule Student",
    href: "/managements/student/schedule",
    icon: CalendarDays,
    visibility: true,
  },
  {
    title: "Library Digital Student",
    href: "/managements/student/library",
    icon: Library,
    visibility: true,
  },
  {
    title: "Profile Student",
    href: "/managements/student/profile",
    icon: UserPen,
    visibility: false,
  },
  {
    title: "Laporan Presensi Student",
    href: "/managements/student/profile-presence",
    icon: UserPen,
    visibility: false,
  },
  {
    title: "Laporan Nilai Student",
    href: "/managements/student/profile-value",
    icon: UserPen,
    visibility: false,
  },
  {
    title: "Pembayaran SPP Student",
    href: "/managements/student/profile-payment",
    icon: UserPen,
    visibility: false,
  },
  // {
  //   title: "Pengumuman",
  //   href: "/dashboard/announcements",
  //   icon: BookMarked,
  // },
  // {
  //   title: "Sekolah",
  //   href: "/dashboard/schools",
  //   icon: SchoolIcon,
  // },
];
