name: Auto-Deploy to Server

on:
  push:
    branches:
      - main  # Jalankan hanya saat push ke branch `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup SSH Key for Deployment
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # Step 3: Deploy Files to Server
      - name: Deploy to Server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@147.93.97.44:/frontend
